apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mpkx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mpkx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mpkx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mpkx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mpkx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nlbp-tenant/rhtap-demo-app/hacbs-test-project-mpkx@sha256:ac18f0b351a29c0e805d57da65a4ce14a5ba02ff0486ea4c4ba59e5b4d1d6fbe
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
